# Generated by Django 6.0 on 2026-01-05 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_consultation_motif_doctor_nom_doctor_prenom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossiermedical',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='dossiers_medicaux/'),
        ),
    ]
