# Generated by Django 6.0 on 2026-01-16 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_dossiermedical_fichier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_facture', models.CharField(max_length=50, unique=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('PAYEE', 'Payée'), ('EN_ATTENTE', 'En attente'), ('ANNULEE', 'Annulée')], default='EN_ATTENTE', max_length=20)),
                ('methode_paiement', models.CharField(blank=True, choices=[('ESPECES', 'Espèces'), ('CARTE', 'Carte bancaire'), ('CHEQUE', 'Chèque'), ('VIREMENT', 'Virement')], max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_paiement', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures', to='users.consultation')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='users.patient')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
